namespace VManagement.Database.Command
{
    /// <summary>
    /// Factory utilizada para nomes autogerados de parâmetros para comandos SQL.
    /// </summary>
    public class ParameterNameFactory
    {
        /// <summary>
        /// O formato padrão dos parâmetros autogerados.
        /// </summary>
        public const string ParameterNameLayout = "@{0}_{1}_AUTOGENERATED";

        private static int _parameterIndex = 0;

        /// <summary>
        /// Gera o nome de um parâmetro para um comando SQL. É possível informar um identificador para o parâmetro.
        /// </summary>
        /// <param name="paramIdentifier">Identificador que será utilizado.</param>
        /// <returns>O nome do parâmetro autogerado.</returns>
        public static string NewParameter(string paramIdentifier = "NOTSET")
        {
            int thisIndex = Interlocked.Increment(ref _parameterIndex);
            return string.Format(ParameterNameLayout, thisIndex, paramIdentifier);
        }
    }
}
